apiVersion: v1
kind: ConfigMap
metadata:
  name: init-postgres
  namespace: appstore
data:
  Init-Postgres.sql: "DROP SCHEMA IF EXISTS \"appstore\";\nCREATE SCHEMA \"appstore\";"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appstore-backend-config
  namespace: appstore
data:
  JDBC_DATABASE_URL: "jdbc:postgresql://postgres-postgresql.appstore.svc.cluster.local:5432/appstore"
  JDBC_DATABASE_USERNAME: You
  JDBC_DATABASE_PASSWORD: SuperSecure
  OPA_URL: "http://kelon.kelon.svc.cluster.local:8181/v1/data/http/authz/allow"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appstore-frontend-config
  namespace: appstore
data:
  BACKEND_URL: "http://localhost:8080"
